### ISSUE TITLE
当App中Sky层为透明svg图片时，如何触发tree和ground的点击事件？

### ISSUE THREAD

**Issue by ZhuFaRuHuan** [leaferjs/leafer-ui#187]
如题，如何才能穿透sky层的svg图片点击到tree层的按钮？
如果将sky层的hittable设置为false 又无法响应滚轮和平移操作了，试了文档中的各种设置都无法实现。

**Comment by leaferjs** [comment]
将svg图片的hittable设置为false应该就行。另外不知道你有没有注意到，如果将svg图片的hitFill 设为pixel，可以穿过svg的透明区域点中下方的元素：

https://www.leaferjs.com/ui/reference/property/hit.html#hitfill-ihittype

**Comment by ZhuFaRuHuan** [comment]
感谢！居然还有这么牛的功能，我正在想怎么给封闭透明的Line加点击事件，因为我发现默认透明的地方触发不了。
不过这文档也太神奇了，我看了好多遍但你发的页面都是我没见过的。。。。。

**Comment by leaferjs** [comment]
哈哈哈，得按照左侧菜单挨个看才行（不过你不用的时候，看了也可能会记不住）
