### ISSUE TITLE
对自动宽度TEXT对齐行为的一点建议

### ISSUE THREAD

**Issue by ZhuFaRuHuan** [leaferjs/leafer-ui#188]
当TEXT设置为自动宽度时，发现textAlign='center' 和 textAlign='right' 会改变Text的实际坐标，表现为boxBounds.x为负值。这时如果想让Text的x回到原来的位置需要 text.x = text.x - text.boxBounds.x
这样的对齐方式虽然是主流图像编辑器如:PS的默认行为，但感觉对编程并不友好。自动宽度的 textAlign 建议只对多行文本生效，一般使用场景也多是用在多行段落对齐上，见下图：
![未标题-1](https://github.com/user-attachments/assets/5f3bfd1a-7e33-4028-a61a-1afea52c8fcb)

只是一点小建议。

**Comment by leaferjs** [comment]
感谢反馈，有好几个人提过，看来可以增加个配置满足这种情况。

目前做编辑器的人比较多（我看PS/Sketch/Figma都是采用这种方式），之前的还是得保持有。

**Comment by leaferjs** [comment]
已支持配置autoSizeAlign实现：https://www.leaferjs.com/ui/reference/display/Text.html#autosizealign-boolean
