### ISSUE TITLE
hittable的hitFill: 'pixel'像素检测不精确

### ISSUE THREAD

**Issue by leidao** [leaferjs/leafer-ui#217]
<img width="317" alt="image" src="https://github.com/user-attachments/assets/b96596f4-442d-45ab-8b4e-f50b75175ea9">

https://cloudstudio.net/a/21567131334545408?channel=share&sharetype=URL

如图，鼠标在经过框出来的区域时没有触发事件，像素检测不够精准。

**Comment by leaferjs** [comment]
我看了一下，只有边框有内容，中间是挖空的，你得填充内容才能触发，

**Comment by leidao** [comment]
<img width="543" alt="image" src="https://github.com/user-attachments/assets/b72b08ec-b3d2-4615-8c6f-7ce379bb7f33">

如图，鼠标在上下两边也没有触发事件，并不是指鼠标经过中间挖空的内容

**Comment by leaferjs** [comment]
测试了下，有特定触发条件，后面会修复下，感谢反馈～

**Comment by leaferjs** [comment]
已修复，快去升级下新版本～
