### ISSUE TITLE
new Frame重置尺寸  元素能不能同步缩放

### ISSUE THREAD

**Issue by yy8z7** [leaferjs/leafer-ui#219]
new Frame重置尺寸  元素能不能同步缩放

**Comment by leaferjs** [comment]
设置 resizeChildren
https://www.leaferjs.com/ui/reference/property/resize.html#resizechildren-boolean

**Comment by yy8z7** [comment]
![image](https://github.com/user-attachments/assets/2da150f4-dcc6-482b-9b89-3c4d95207091)     如果禁用zoom缩放好像就不同步了 是不是

**Comment by yy8z7** [comment]
能不能 设置 双指不给缩放画布

**Comment by leaferjs** [comment]
目前只能禁用wheel事件，或者直接禁用zoom

**Comment by leaferjs** [comment]
> 能不能 设置 双指不给缩放画布

增加了一个设置可以关闭： https://www.leaferjs.com/ui/reference/config/app/multiTouch.html
