### ISSUE TITLE
增加父元素宽度后，如何优雅地把空白加到左侧

### ISSUE THREAD

**Issue by acbv12** [leaferjs/leafer-ui#223]
RT
增加元素宽度后，希望把空白加在左边；
可以想到的方法是把所有的子元素的位置右移增加的宽度值，但是不太优雅。有没有优雅地实现。

**Comment by leaferjs** [comment]
可以看一下Bounds类的spread方法：

https://www.leaferjs.com/ui/reference/math/Bounds.html#spread-fournumber-ifournumber-bounds

**Comment by acbv12** [comment]
没有太明白哦；这个可以生成一个新的边界值，拿到新的边界值也只能给父元素设置期望的边界值吧
