### ISSUE TITLE
在小程序 skyline 渲染引擎下不能获取节点

### ISSUE THREAD

**Issue by beetaa** [leaferjs/leafer-ui#225]
在小程序 skyline 引擎下无法获取节点实例，无法启动。

![image](https://github.com/user-attachments/assets/81300eb2-e81c-44e0-b8c4-3d41ea9944b7)

**Comment by leaferjs** [comment]
先按照官网的小程序示例操作～

**Comment by beetaa** [comment]
可以了，view 的 id 值打错别字了，谢谢。
