### ISSUE TITLE
如何获取到框选的的边界的x,y的位置呢

### ISSUE THREAD

**Issue by daLeiStrive** [leaferjs/leafer-ui#228]
`const { width, height, x, y } = leafer.editor.editBox.rect`
如上代码发现x y 都是 0 
只能获取宽高

![e99896e04b856fc0c5987cb623caca5](https://github.com/user-attachments/assets/91f4794f-febd-4266-b605-a7fd3cdd019f)

**Comment by leaferjs** [comment]
可以通过editor.element.x 获取，或通过包围盒获取： https://www.leaferjs.com/ui/reference/property/bounds.html

**Comment by daLeiStrive** [comment]
好的,感谢感谢
