### ISSUE TITLE
请教：浏览器兼容性

### ISSUE THREAD

**Issue by blackstar-baba** [leaferjs/leafer-ui#230]
如题，看到作者的经历，非常敬佩作者，目前也在用业余时间做一些事情，涉及到多个浏览器，想用咱们的产品，想咨询下咱们产品目前可以在哪些浏览器上使用，兼容性如何，感谢您的时间。

**Comment by leaferjs** [comment]
https://www.leaferjs.com/ui/guide/install/ui/start.html#%E6%B5%8F%E8%A7%88%E5%99%A8%E7%8E%AF%E5%A2%83

![image](https://github.com/user-attachments/assets/fd940069-1aac-4ed9-a6bb-85151b96d936)
