### ISSUE TITLE
文字怎么自动进入编辑状态，可修改文字内容

### ISSUE THREAD

**Issue by 3400442579** [leaferjs/leafer-ui#231]
如题？

**Comment by leaferjs** [comment]
安装一下文本编辑插件： https://www.leaferjs.com/ui/plugin/in/text-editor/

**Comment by 3400442579** [comment]
这个要双击 才进入 文字内容 编辑，怎么实现 创建文字后，直接进入 文字内容编辑 状态，修改文字

**Comment by leaferjs** [comment]
有手动打开文本编辑器的方法editor.openInnerEditor(text)： https://www.leaferjs.com/ui/plugin/in/editor/Editor.html#%E5%86%85%E9%83%A8%E7%BC%96%E8%BE%91
