### ISSUE TITLE
微信小程序触发点偏移问题

### ISSUE THREAD

**Issue by yurande** [leaferjs/leafer-ui#232]
我在使用uniapp开发微信小程序。设置页面view中的canvas为宽800，高450，在设置leafer app 时为：宽1600，高900，在实际预览中，控制点会偏向右下脚一定距离，x越小，距离越小，x越大，距离越大，请问有没有像微信小程序中 canvas 逻辑尺寸的设置？

**Comment by leaferjs** [comment]
微信小程序只能通过css设置尺寸，可以看一下小程序的示例，默认会自动适配高清屏，或者手动指定屏幕像素比app.config.pixelRatio

**Comment by yurande** [comment]
感谢回复，我想要的效果是让不同设备显示一样的内容（比如像图片一样可以设置等比缩放）。我试过设置 app.config.pixelRatio ，但在不同设备，由于canvas的尺寸不同，显示元素的大小和位置是不一样的，我现在想的处理方式是将元素的大小和坐标 除于 pixelRatio，请问有没有更好的办法？

**Comment by leaferjs** [comment]
看看这个视图控制插件，zoom('fit') 会自动帮你处理: https://www.leaferjs.com/ui/plugin/in/view/zoom.html

**Comment by yurande** [comment]
感谢回答，试过这个插件了，感觉还是解决不了我的问题，因为我需要把元素的位置大小这些数据保存在外部文件中，然后在其他设备，其他不使用leafer的app中也能绘制出来，之前是自己用canvas绘制的，使用的是百分比保存的，现在也要兼容以前的文件，所以还是继续使用百分比保存和绘制了，问题已经解决了，非常感谢
