### ISSUE TITLE
Text 将 moveable 设为false，无法触发编辑效果

### ISSUE THREAD

**Issue by MellowCo** [leaferjs/leafer-ui#237]
https://cloudstudio.net/a/22262695923044352?channel=share&sharetype=URL

textUI2 想实现固定位置，但是可以编辑文字，设置 moveable 为false，无法触发编辑效果

![image](https://github.com/user-attachments/assets/71cee985-e505-4eb7-9739-59505d0e0cbb)

**Comment by leaferjs** [comment]
收到，谢谢反馈～，下个版本修复一下，可以先监听双击事件，手动打开文本编辑工具:

https://www.leaferjs.com/ui/plugin/in/editor/Editor.html#openinnereditor-target-ui-select-boolean
