### ISSUE TITLE
Group能不能支持hitBox属性

### ISSUE THREAD

**Issue by gcming** [leaferjs/leafer-ui#240]
目前Group不支持hitBox，当多个元素组合的时候，group框内的元素以及空白都应该也可以允许拖动

**Comment by leaferjs** [comment]
后面可以支持一下～

**Comment by gcming** [comment]
目前group内的空白元素有没有方法也可以设置允许拖动呢

**Comment by gcming** [comment]
> 后面可以支持一下～

目前group内的空白元素有没有方法也可以设置允许拖动呢

**Comment by leaferjs** [comment]
可以改用Box代替Group,  给Box设置hitFill = ‘all' 就可以实现整体拖动

**Comment by gcming** [comment]
嗯嗯好的，谢谢！

**Comment by jdpoccorie** [comment]
Perhaps this solution will help you figure out the problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)
