### ISSUE TITLE
[bug] 控制出现大量日志

### ISSUE THREAD

**Issue by Ronbb** [leaferjs/leafer-ui#242]
@leafer-ui/draw/lib/draw.esm.js

console.log(bounds, autoWidth, autoHeight)

看起来像是调试日志忘了删？

**Comment by leaferjs** [comment]
抱歉，可能是忘删除了😂，一会儿再更新一个版本，后面看加个自动检测的功能

**Comment by leaferjs** [comment]
修复了，v1.0.9 版本已更新，可以去安装下～
