### ISSUE TITLE
[Bug] 拖拽添加元素时App实例无法触发drop事件，而Leafer实例可以

### ISSUE THREAD

**Issue by cbly666** [leaferjs/leafer-ui#245]
![image](https://github.com/user-attachments/assets/9daed999-016f-48da-8e4e-517f1901d1f6)

完整代码如下：
https://cloudstudio.net/a/22705321292918784?channel=share&sharetype=URL

**Comment by leaferjs** [comment]
刚调试了一下，把canvas改成div标签就可以了，App最好用div标签作为view（会自动添加两个canvas层到dom中，否则会多产生一次合并绘制）：
![image](https://github.com/user-attachments/assets/1a993e85-ba13-4c92-8c75-2c4136fb9000)
