### ISSUE TITLE
小程序版Png图片有黑色描边

### ISSUE THREAD

**Issue by jkin8010** [leaferjs/leafer-ui#246]
在小程序版中，使用Image添加PNG图片时，图片的Alpha通道显示有黑色描边，如何去除PNG的描边呢？
<img width="501" alt="image" src="https://github.com/user-attachments/assets/dafd208e-e5d9-4493-bbbb-a6c9e0d1fc35">

**Comment by leaferjs** [comment]
已在技术交流群回复～
