### ISSUE TITLE
配合Taro 3.x 使用 @leafer-ui/miniapp 1.0.8 包含更高版本时，useCanvas方法 和 view配置项报错

### ISSUE THREAD

**Issue by qing-yu-an** [leaferjs/leafer-ui#248]
useCanvas方法报错：
![image](https://github.com/user-attachments/assets/4a88d1f7-0d3f-4978-a61e-32ddf5f0cc79)

Leafer配置项view报错：
![image](https://github.com/user-attachments/assets/216c4faf-bac4-4816-8b4f-7fd5078428b7)

解决方式：@leafer-ui/miniapp 降到 1.0.5 上述问题消失

**Comment by leaferjs** [comment]
收到，谢谢反馈～

**Comment by leaferjs** [comment]
这两天会更新一个版本

**Comment by leaferjs** [comment]
v1.0.10昨晚发布了，问题已经修复～
