### ISSUE TITLE
我创建了一个可以编辑的矩形框然后在children属性中添加了一个文本，为什么页面上没有绘制这个文本呢

### ISSUE THREAD

**Issue by Pangchengqiu12** [leaferjs/leafer-ui#249]
我创建了一个可以编辑的矩形框然后在children属性中添加了一个文本，为什么页面上没有绘制这个文本呢
![微信截图_20241113112609](https://github.com/user-attachments/assets/462fa6c0-d9fa-4042-bde9-7d3c882e60fa)
![微信截图_20241113112629](https://github.com/user-attachments/assets/042f502f-194d-4cb5-bc45-36683c8032fc)

**Comment by leaferjs** [comment]
Rect不支持添加子级， 用Box代替就可以了
