### ISSUE TITLE
【bug？】微信小程序，根据文档步骤，项目报错

### ISSUE THREAD

**Issue by bran-nie** [leaferjs/leafer-ui#255]
声明，我个人也赞同，小程序很不友好

首先，在微信开发者工具中，新创建一个小程序项目。根据文档中，「快速安装」小程序部分，install 本依赖，并勾选 js 转换为 ES5，也将 miniProjram_npm 中，查找出来的内容进行替换。

其次，直接复制「体验」中的第一个代码，发现跑不起来。

也查看文档中[常见问题](https://www.leaferjs.com/ui/guide/problem/)中，涉及到小程序的那个。

![image](https://github.com/user-attachments/assets/0eccac8d-f6a7-4299-a6a3-d5b31d2879f5)

**Comment by leaferjs** [comment]
安装v1.0.5试试：

https://github.com/leaferjs/leafer-ui/issues/248

**Comment by leaferjs** [comment]
应该是插件版本也需要用1.0.5。

可以直接安装 leafer-editor 包，包含了编辑器插件。

**Comment by leaferjs** [comment]
这周会再更新一个版本，复杂的海报编辑功能，建议最好还是用webview方式

**Comment by bran-nie** [comment]
> 应该是插件版本也需要用1.0.5。
> 
> 可以直接安装 leafer-editor 包，包含了编辑器插件。

插件我也是用的相同版本，1.0.5

**Comment by hj-long** [comment]
换成v1.0.5版本的确实可以跑demo了，但是看了一下包的体积还是挺大的差不多1m

**Comment by hj-long** [comment]
希望后面可以出一个按需加载的版本，这样就很完美了

**Comment by leaferjs** [comment]
> 换成v1.0.5版本的确实可以跑demo了，但是看了一下包的体积还是挺大的差不多1m

那是开发版的，打包后只有200kb左右，你也可以直接引用min.js

**Comment by leaferjs** [comment]
v1.0.10昨晚发布了，问题已经修复～
