### ISSUE TITLE
求大佬解答！！

### ISSUE THREAD

**Issue by z222222ha** [leaferjs/leafer-ui#273]
![image](https://github.com/user-attachments/assets/bb938b59-b42a-4fd4-9e39-63b134a52ae4)
（底图和元素都是通过 Rect-fill-image 加载的）
问：
1、这种 2.5d 视角是否需要构建特殊的坐标系？
2、如何将图中的那个柜子限制只能在底部米色区域中拖动？

**Comment by leaferjs** [comment]
可以自己将2D坐标点转换为3D坐标点，这种2.5D应该是有一个固定的矩阵

也可以通过2d的旋转加倾斜模拟一个父级的容器和子元素，然后给子元素设置dragBounds：'parent' 限制拖拽，再把坐标点转换出来，同步给外面的这个盒子

**Comment by liesauer** [comment]
很抱歉打扰了，@leaferjs 请问这种伪3D或真3D有插件或者官方有计划在做吗，自己做底层的这些东西有点超标了(⊙o⊙)…
