### ISSUE TITLE
导入失败

### ISSUE THREAD

**Issue by liangyao375** [leaferjs/leafer-ui#281]
导入后没反应，空白
``` vue
<template>
  <div id="leafer-view"></div>
</template>

<script setup lang="ts">
import { Leafer } from "leafer-ui";
import { onMounted } from "vue";
onMounted(() => {
  const leafer = new Leafer({ view: "leafer-view" });

  const json = {
    tag: "Leafer",
    hittable: true,
    fill: "#242424",
    children: [
      {
        tag: "Text",
        fill: "rgba(255, 255, 255, 0.87)",
        text: "Vue + Vite + LeaferJS",
        fontFamily: "Inter, system-ui, Avenir, Helvetica, Arial, sans-serif",
        fontSize: 35,
      },
      {
        tag: "Text",
        fill: "#888",
        text: "Double-click on the LeaferJS logo to learn more.",
        fontFamily: "Inter, system-ui, Avenir, Helvetica, Arial, sans-serif",
        fontSize: 20,
      },
      {
        tag: "Text",
        fill: "#888",
        text: "Move View : scroll wheel or hold mouse wheel while dragging",
        fontFamily: "Inter, system-ui, Avenir, Helvetica, Arial, sans-serif",
        fontSize: 20,
      },
      {
        tag: "Text",
        fill: "#888",
        text: "Zoom View : alt + mouse wheel",
        fontFamily: "Inter, system-ui, Avenir, Helvetica, Arial, sans-serif",
        fontSize: 20,
      },
    ],
  };
  
  leafer.add(json);
});
</script>
```

**Comment by liangyao375** [comment]
还有个问题changeAttr和导入一起使用，没起作用

**Comment by liangyao375** [comment]
好的，创建方式和set方式有什么不同吗？创建方式我用文档的json就能导入，用我上面的json(脚手架里的)就没法导入
![image](https://github.com/user-attachments/assets/ff184d87-f0be-4006-bdb7-f115834f9372)

**Comment by liangyao375** [comment]
```vue
<template></template>

<script setup lang="ts">
import { Leafer, Rect } from "leafer-ui";
import { onMounted } from "vue";
onMounted(() => {
  const json = { id: "aa", tag: "Leafer", children: [{ tag: "Rect", x: 100, y: 100, draggable: true, fill: "#32cd79" }] };
  Rect.changeAttr("draggable", false);
  const leafer = new Leafer({ view: window });
  leafer.set(json);
});
</script>

<style scoped></style>
```
这样的话没起作用，我的需求是想把所有元素的draggable都设置成false

**Comment by Ronbb** [comment]
> ```vue
> <template></template>
> 
> <script setup lang="ts">
> import { Leafer, Rect } from "leafer-ui";
> import { onMounted } from "vue";
> onMounted(() => {
>   const json = { id: "aa", tag: "Leafer", children: [{ tag: "Rect", x: 100, y: 100, draggable: true, fill: "#32cd79" }] };
>   Rect.changeAttr("draggable", false);
>   const leafer = new Leafer({ view: window });
>   leafer.set(json);
> });
> </script>
> 
> <style scoped></style>
> ```
> 
> 这样的话没起作用，我的需求是想把所有元素的draggable都设置成false

看起来数据里是 `tag: "Leafer"`，但是修改属性改的是 `Rect`

**Comment by liangyao375** [comment]
还有就是用脚手架导出的json，在导入会提示类型错误，目前看到错误的有fontWeight、flow、flowAlign
![image](https://github.com/user-attachments/assets/c23f0bd8-ca64-49fe-a46e-4df5dbedf04a)

**Comment by liangyao375** [comment]
> > ```vue
> > <template></template>
> > 
> > <script setup lang="ts">
> > import { Leafer, Rect } from "leafer-ui";
> > import { onMounted } from "vue";
> > onMounted(() => {
> >   const json = { id: "aa", tag: "Leafer", children: [{ tag: "Rect", x: 100, y: 100, draggable: true, fill: "#32cd79" }] };
> >   Rect.changeAttr("draggable", false);
> >   const leafer = new Leafer({ view: window });
> >   leafer.set(json);
> > });
> > </script>
> > 
> > <style scoped></style>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 这样的话没起作用，我的需求是想把所有元素的draggable都设置成false
> 
> 看起来数据里是 `tag: "Leafer"`，但是修改属性改的是 `Rect`。数据里`Rect`写入了`draggable: true`。文档里写的`changeAttr`改的是默认值。

跟tag没关系吧，changeAttr里写的应该是元素名。如果只是改默认值的话，那确实不能用changeAttr，那我应该用什么方法？

**Comment by Ronbb** [comment]
> 还有就是用脚手架导出的json，在导入会提示类型错误，目前看到错误的有fontWeight、flow、flowAlign ![image](https://private-user-images.githubusercontent.com/55582967/393067992-c23f0bd8-ca64-49fe-a46e-4df5dbedf04a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0NTI1MDMsIm5iZiI6MTczMzQ1MjIwMywicGF0aCI6Ii81NTU4Mjk2Ny8zOTMwNjc5OTItYzIzZjBiZDgtY2E2NC00OWZlLWE0NmUtNGRmNWRiZWRmMDRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA2VDAyMzAwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlMTBjZjE4MDVkMWQxODU0YWUxMTc2NzRmNjhlYjFmODgxNGZiN2JhY2ViZTA5MTJmNDUxYWQ4YmZjNGU1NGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.JaNjCpdNLHHQITNUebZScfTwyzH8V4mysxh9HRV-Uvs) <img alt="image" width="876" src="https://private-user-images.githubusercontent.com/55582967/393068810-fd75b545-d7c0-4d1e-96fa-bab6270c67c5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0NTI1MDMsIm5iZiI6MTczMzQ1MjIwMywicGF0aCI6Ii81NTU4Mjk2Ny8zOTMwNjg4MTAtZmQ3NWI1NDUtZDdjMC00ZDFlLTk2ZmEtYmFiNjI3MGM2N2M1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA2VDAyMzAwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiNDliMDRjOTZjODA0NWFjODUwMDliMmQ4NTQ2MzY1Nzk3YTJiYzg0M2EwMWJiYzEyOWE2MmE0YzY1OGY3NTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Ckv3nUmoCD7VgApDnI0yTIltBe5ZnBceqXvwN-ZsmSs">

这个是 typescript的限制吧

比如这样是不行的，因为x类型的类型被认为是string
```typescript
type Input = { x: 'x' }

const fn = (input: Input) => {}

const input = { x: 'x' }

fn(input)
```

要改成这样：

```typescript
type Input = { x: 'x' }

const fn = (input: Input) => {}

const input = { x: 'x' } as const

fn(input)

```

**Comment by Ronbb** [comment]
> > > ```vue
> > > <template></template>
> > > 
> > > <script setup lang="ts">
> > > import { Leafer, Rect } from "leafer-ui";
> > > import { onMounted } from "vue";
> > > onMounted(() => {
> > >   const json = { id: "aa", tag: "Leafer", children: [{ tag: "Rect", x: 100, y: 100, draggable: true, fill: "#32cd79" }] };
> > >   Rect.changeAttr("draggable", false);
> > >   const leafer = new Leafer({ view: window });
> > >   leafer.set(json);
> > > });
> > > </script>
> > > 
> > > <style scoped></style>
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 这样的话没起作用，我的需求是想把所有元素的draggable都设置成false
> > 
> > 
> > 看起来数据里是 `tag: "Leafer"`，但是修改属性改的是 `Rect`。数据里`Rect`写入了`draggable: true`。文档里写的`changeAttr`改的是默认值。
> 
> 跟tag没关系吧，changeAttr里写的应该是元素名。如果只是改默认值的话，那确实不能用changeAttr，那我应该用什么方法？

是的tag我一开始看错了。要么你不要传`draggable: true`，要么这样写一个新元素继承已有的元素，在构造函数里屏蔽draggable输入。

**Comment by liangyao375** [comment]
> > > > ```vue
> > > > <template></template>
> > > > 
> > > > <script setup lang="ts">
> > > > import { Leafer, Rect } from "leafer-ui";
> > > > import { onMounted } from "vue";
> > > > onMounted(() => {
> > > >   const json = { id: "aa", tag: "Leafer", children: [{ tag: "Rect", x: 100, y: 100, draggable: true, fill: "#32cd79" }] };
> > > >   Rect.changeAttr("draggable", false);
> > > >   const leafer = new Leafer({ view: window });
> > > >   leafer.set(json);
> > > > });
> > > > </script>
> > > > 
> > > > <style scoped></style>
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > 这样的话没起作用，我的需求是想把所有元素的draggable都设置成false
> > > 
> > > 
> > > 看起来数据里是 `tag: "Leafer"`，但是修改属性改的是 `Rect`。数据里`Rect`写入了`draggable: true`。文档里写的`changeAttr`改的是默认值。
> > 
> > 
> > 跟tag没关系吧，changeAttr里写的应该是元素名。如果只是改默认值的话，那确实不能用changeAttr，那我应该用什么方法？
> 
> 是的tag我一开始看错了。要么你不要传`draggable: true`，要么这样写一个新元素继承已有的元素，在构造函数里屏蔽draggable输入。

对我这个场景不太可行，我的需求是导出的json，再次导入的时候不让拖拽编辑
