### ISSUE TITLE
请问 如何实现流动的线

### ISSUE THREAD

**Issue by yyyyh** [leaferjs/leafer-ui#290]
类似这样流动的线，可自定义背景和线段的颜色等样式
![PixPin_2024-12-13_15-38-34](https://github.com/user-attachments/assets/b1e7e819-f439-4a55-8789-136b51ace7e4)

**Comment by leaferjs** [comment]
流动的线用 dashOffset 循环动画 + 虚线就能实现：

https://www.leaferjs.com/ui/reference/property/stroke.html#dashpattern-number

**Comment by yyyyh** [comment]
> 流动的线用 dashOffset 循环动画 + 虚线就能实现：
> 
> https://www.leaferjs.com/ui/reference/property/stroke.html#dashpattern-number

感谢 已经实现了

**Comment by yyyyh** [comment]
> 流动的线用 dashOffset 循环动画 + 虚线就能实现：
> 
> https://www.leaferjs.com/ui/reference/property/stroke.html#dashpattern-number

如果是折线的情况下的流动呢？如图
![PixPin_2024-12-16_14-55-02](https://github.com/user-attachments/assets/96da2945-be3e-40f8-8f8f-e46f574461dc)

**Comment by LiuWuTong** [comment]
> > 流动的线用 dashOffset 循环动画 + 虚线就能实现：
> > https://www.leaferjs.com/ui/reference/property/stroke.html#dashpattern-number
> 
> 感谢 已经实现了

请问怎么实现的？ 能指导，贴下相关代码吗
