### ISSUE TITLE
初始化Leafer对象并根据id挂载到div上时，画布的宽高如何跟随div的宽高?

### ISSUE THREAD

**Issue by 1L2018** [leaferjs/leafer-ui#298]
<script setup>
import { onMounted, ref } from 'vue';

import { Leafer, Rect } from 'leafer-editor';

const editorArea = ref(null);
onMounted(() => {
  // eslint-disable-next-line no-console
  console.log(editorArea.value.style);
  const app = new Leafer({
    view: 'editor',
    // width: 800,
    // height: 600,  // 不加宽高会导致画布不断扩大
  });
  app.ground = new Leafer({ type: 'draw' });
  app.tree = new Leafer();
  app.sky = new Leafer({ type: 'draw', usePartRender: false });

  app.add(app.ground);
  app.add(app.tree);
  app.add(app.sky);

  const background = new Rect({ width: 800, height: 600, fill: 'gray' });
  const rect = new Rect({ x: 100, y: 100, fill: '#32cd79', draggable: true });
  const border = new Rect({ x: 200, y: 200, stroke: 'blue', draggable: true });

  app.ground.add(background);
  app.tree.add(rect);
  app.sky.add(border);
});
</script>

<template>
  <div id="editor" ref="editorArea" class="h-full w-full"></div>
</template>

<style lang="scss" scoped></style>

**Comment by 1L2018** [comment]
自动布局时，当父容器的宽度或高度为 100%，同时设置 padding 或 border， 会导致画布不断 resize 扩大。
https://www.leaferjs.com/ui/guide/problem/#%E7%94%BB%E5%B8%83%E4%B8%8D%E6%96%AD%E8%87%AA%E5%8A%A8%E6%89%A9%E5%A4%A7%E5%AF%BC%E8%87%B4%E7%9A%84%E5%8D%A1%E9%A1%BF%E9%97%AE%E9%A2%98

在这里找到这个问答，也发现如果要挂载的元素的宽高使用类似100px的长度指定的话就不会无限扩大，请问我如果要使用100%的话，如何解决呢？

**Comment by liesauer** [comment]
> view参数的dom元素（最好是一个div) 需要通过css设置布局信息，然后不要有padding/border之类的，如果需要设置padding/border可以在外面再包一层。
> 
> 内部原理是监听view元素的clientRect区域变化来进行自动布局leafer的。

内部的canvas大小能根据div的变化而变化吗，我的div是设置的100%，但是leafer初始化后，里面的div和canvas都是设置了初始化时的宽高的，如果我的窗口大小从1000变成500，虽然显示没啥问题，但由于canvas是远超当前屏幕大小的，结果就是`拖拽至边界时自动平移视图`等等的功能判定是不对的，要把鼠标拖到很远的地方才会生效，即宽度为1000的位置。

**Comment by liesauer** [comment]
还有一个问题，我的view上面有一排float的按钮，正常是一排的，但是宽度不够的话会顶下来变两排，这个时候，leafer内部的两个canvas就会偏移，显示层和操作层一个不受影响，一个受影响了，style都是内部管理的，我该怎么处理呢
<img width="1888" height="480" alt="Image" src="https://github.com/user-attachments/assets/2dc71b92-82cb-43ab-9a29-9e11c4f68f2a" />

**Comment by liesauer** [comment]
看视频的话可能会更明白点

https://github.com/user-attachments/assets/690053ce-7633-490e-939b-904bf3d0f3cf

**Comment by liesauer** [comment]
已经通过调整div的结构都解决了👍
